### ISSUE TITLE
`Icon Component` : Missing OnSelect Property

### ISSUE THREAD

**Issue by 6gal6ler6** [microsoft/powercat-code-components#154]
Icon Component does not have `OnSelect`

![image](https://user-images.githubusercontent.com/20881746/209594807-f4ec4ac9-1060-416f-bd44-033d3ce2cb7b.png)

I can see the implementation here: [onSelect at index.ts](https://github.com/microsoft/powercat-code-components/blob/57b81b48f4c9b090dc0f600c849a1b07fd0a4319/Icon/Icon/index.ts#L75) and also here: [onClick prop on RenderButtonAs](https://github.com/microsoft/powercat-code-components/blob/57b81b48f4c9b090dc0f600c849a1b07fd0a4319/Icon/Icon/IconComponent.tsx#L88). But for some reason the prop is not present.

**Used Version** 1.0.19
Used on Canvas App

**Comment by scottdurow** [comment]
Hi @6gal6ler6 - You are right - the Icon component will raise the OnChange event when clicked since field components cannot raise the OnSelect event. 

Simply put the code you would normally put in the OnSelect event, inside the OnChange event. 

Hope this helps
Scott

**Comment by 6gal6ler6** [comment]
HI @scottdurow , thanks for the advice. I have implemented the behaviour as you mentioned and works like a charm
