### ISSUE TITLE
Protecting the beta branch

### ISSUE THREAD

**Issue by scottdurow** [microsoft/powercat-code-components#26]
I suggest that the beta branch is protected with the PR Validation Workflow so that any issues are trapped before they are merged into main. What do you think?
cc @Ramakrishnan24689

**Comment by scottdurow** [comment]
Case in point - I have submitted a PR that is on top of the beta branch - but it has failed due to a check on test unrelated to the PR changes - https://github.com/microsoft/powercat-code-components/actions/runs/3056823509/jobs/4931348326

**Comment by Ramakrishnan24689** [comment]
Thanks for pointing this out. I somehow missed it.

**Comment by scottdurow** [comment]
The beta branch is now protected 🥳
